/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.10.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as clerk from "../clerk.js";
import type * as constants_prompts from "../constants/prompts.js";
import type * as extractions from "../extractions.js";
import type * as files from "../files.js";
import type * as http from "../http.js";
import type * as langchain_db from "../langchain/db.js";
import type * as lib_myllm from "../lib/myllm.js";
import type * as serve from "../serve.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  clerk: typeof clerk;
  "constants/prompts": typeof constants_prompts;
  extractions: typeof extractions;
  files: typeof files;
  http: typeof http;
  "langchain/db": typeof langchain_db;
  "lib/myllm": typeof lib_myllm;
  serve: typeof serve;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
